version: "3.9"
services:
  app:
    container_name: cinema-back
    restart: always
    build: ./
    ports:
      - "3002:3002"
    links:
      - mongo
    environment:
      - HOST=0.0.0.0
      - PORT=3002