apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: cinema-back
  name: cinema-back
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cinema-back
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: cinema-back
    spec:
      containers:
      - image: 579741038344.dkr.ecr.us-east-2.amazonaws.com/cinema-back-repository:1.0.1-beta.1
        name: cinema-back
        imagePullPolicy: Always
        resources: {}
        ports:
          - containerPort: 3002
        env:
          - name: APP_ENV_PG_PASSWORD
            value: mysecretpassword
          - name: APP_ENV_PG_HOST
            value: postgres
status: {}

---

apiVersion: v1
kind: Service
metadata:
  name: cinema-back-service
  labels:
    run: cinema-back-service
spec:
  ports:
  - port: 3002
    targetPort: 3002
    protocol: TCP
  selector:
    app: cinema-back
  type: NodePort